version: "3"

services:
  cyber:
    image: cyberd/cyber:bostrom-localnet-1
    container_name: localbostrom
    #pull_policy: always
    volumes:
      - ./bostrom_config:/root/.cyber/config
      - ./data:/root/.cyber/data
    networks:
      cyber-net:
        ipv4_address: 172.28.1.2
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
    command: cyber start --compute-gpu=false

networks:
  cyber-net:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.28.1.0/24
